sudo: required
dist: trusty
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
    - ROSINSTALL_FILENAME=rosindustrial.rosinstall
    - ROS_PARALLEL_JOBS=-j4
  matrix:
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=debian
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh

